---
settings:
  name: ONTAP tools for VMware vSphere 10
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '10.3'
    url: "/ontap-tools-vmware-vsphere-103"
  - version-number: '10.4'
    url: "/ontap-tools-vmware-vsphere-10"
  - version-number: '10.2'
    url: "/ontap-tools-vmware-vsphere-102"
  - version-number: '10.1'
    url: "/ontap-tools-vmware-vsphere-101"
  - version-number: '10.0'
    url: "/ontap-tools-vmware-vsphere-100"
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Herramientas de ONTAP para documentos de VMware vSphere 10,3
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - section: upgrade
  - section: migrate
  - section: automation
  - title: Avisos legales
    url: "/legal-notices.html"
