---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Cuando se migran datos de almacenamiento, los back-ends de almacenamiento se incorporan manualmente mediante las API DE REST. Cuando se migran datos del proveedor VASA, los datos se exportan desde la base de datos de Derby existente e se importan a la base de datos MongoDB. 
---
= Migre desde ONTAP Tools para VMware vSphere 9.xx a 10,3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mover las herramientas NetApp ONTAP para la configuración de VMware vSphere de la versión 9.xx a la 10.x requiere un proceso de migración debido a las importantes actualizaciones y mejoras del producto en las versiones.

Puede migrar desde las herramientas de ONTAP para las versiones de VMware vSphere 9.12D1 y 9.13D2 a 10,3.

Si tiene almacenes de datos NFS y VMFS, pero no almacenes de datos VVols en su configuración, simplemente desinstale ONTAP Tools 9.xx e implemente ONTAP Tools 10.x. Sin embargo, si su configuración contiene almacenes de datos VVols, deberá migrar el proveedor VASA y el SRA.

La siguiente tabla describe el proceso de migración en estos dos escenarios diferentes.

|===
| *Si la configuración tiene almacenes de datos vVols* | *Si la configuración solo contiene almacenes de datos NFS y VMFS* 


| Pasos: 1. link:../migrate/sra-vasa-migration.html["Migrar el proveedor VASA"] 2.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Crear políticas de almacenamiento de máquinas virtuales"] | Pasos: 1. Elimine las herramientas ONTAP 9.xx de su entorno. Consulte  https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment["Cómo eliminar OTV 9.xx de tu entorno"] Artículo de la base de conocimientos de NetApp. 2. link:../deploy/quick-start.html["Implementar y configurar herramientas ONTAP para VMware vSphere 10.3"] 3. link:../migrate/sra-vasa-migration.html["Actualice el SRA"] 4.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Crear políticas de almacenamiento de máquinas virtuales"] 
|===

NOTE: Después de migrar desde herramientas ONTAP para VMware vSphere 9.xx a 10,3, los almacenes de datos vVols que usan el protocolo NVMe/FC dejan de funcionar, ya que las herramientas de ONTAP 10,3 solo admiten el protocolo NVMe-oF con almacenes de datos VMFS.
