---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Debe configurar un almacén de datos de marcador de posición para que conserve un lugar en el inventario de vCenter en el sitio de recuperación de la máquina virtual protegida \(VM\). El almacén de datos de marcador de posición no tiene por qué ser grande, ya que los marcadores de posición son pequeños y utilizan solo unos pocos cientos o menos kilobytes.' 
---
= Configure almacenes de datos de marcadores de posición
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar un almacén de datos de marcador de posición para que contenga un lugar en el inventario de vCenter en el sitio de recuperación de la máquina virtual protegida. El almacén de datos de marcador de posición no tiene por qué ser grande, ya que los marcadores de posición son pequeños y utilizan solo unos pocos cientos o menos kilobytes.

.Antes de empezar
* Debe haber conectado los sitios protegidos y de recuperación.
* Debe haber configurado las asignaciones de recursos.


.Pasos
. Inicie sesión en vCenter Server y seleccione *Site Recovery* > *Sites*.
. Seleccione su sitio protegido y seleccione *Administrar*.
. Seleccione *Placeholder datastores* > *New* en la pestaña Administrar para crear un nuevo almacén de datos de marcador de posición.
. Seleccione el almacén de datos apropiado y seleccione *OK*.
+

NOTE: Los almacenes de datos de marcador de posición pueden ser locales o remotos y no deben replicarse.

. Repita los pasos 3 a 5 para configurar un almacén de datos de marcador de posición para el sitio de recuperación.

