---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: Debe crear grupos de protección para proteger un grupo de máquinas virtuales en el sitio protegido. 
---
= Configuración de sitios protegidos y de recuperación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear grupos de protección para proteger un grupo de máquinas virtuales en el sitio protegido.



== Configure los grupos de protección

.Antes de empezar
Debe asegurarse de que los sitios de origen y destino están configurados para lo siguiente:

* Misma versión de VMware Live Site Recovery instalada
* Equipos virtuales
* Sitios protegidos y de recuperación emparejados
* Los almacenes de datos de origen y destino deben montarse en las ubicaciones respectivas


.Pasos
. Inicie sesión en vCenter Server y, a continuación, seleccione *Site Recovery* > *Protection Groups*.
. En el panel *Grupos de protección*, selecciona *Nuevo*.
. Especifique un nombre y una descripción para el grupo de protección, la dirección y seleccione *Siguiente*.
. En el campo *Type*, seleccione la opción *Type field...* como grupos de Datastore (replicación basada en array) para el almacén de datos NFS y VMFS. El dominio de fallo no es más que SVM con replicación habilitada. Se muestran las SVM que solo tienen implementadas las relaciones entre iguales y no tienen problemas.
. En la pestaña Grupos de replicación, seleccione el par de matrices habilitado o los grupos de replicación que tienen la máquina virtual configurada y, a continuación, seleccione *Siguiente*.
+
Todas las máquinas virtuales del grupo de replicación se agregan al grupo de protección.

. Seleccione el plan de recuperación existente o cree un nuevo plan seleccionando *Añadir a nuevo plan de recuperación*.
. En la pestaña Listo para completar, revise los detalles del grupo de protección que creó y luego seleccione *Finalizar*.




== Sitios protegidos para pares y de recuperación

Debe emparejar los sitios protegidos y de recuperación creados mediante vSphere Client para habilitar el Storage Replication Adapter (SRA) para detectar los sistemas de almacenamiento.

.Antes de empezar
* Debe tener VMware Live Site Recovery instalado en los sitios protegidos y de recuperación.
* Debe tener el SRA instalado en los sitios protegidos y de recuperación.


.Pasos
. Haga doble clic en *Site Recovery* en la página de inicio de vSphere Client y seleccione *Sites*.
. Selecciona *Objetos* > *Acciones* > *Emparejar sitios*.
. En el cuadro de diálogo *Emparejar servidores de Site Recovery Manager*, introduzca la dirección del controlador de servicios de plataforma del sitio protegido y, a continuación, seleccione *Siguiente*.
. En la sección Select vCenter Server, realice lo siguiente:
+
.. Compruebe que vCenter Server del sitio protegido aparece como candidato coincidente al emparejar.
.. Introduzca las credenciales administrativas de SSO y, a continuación, seleccione * Finalizar *.


. Si se le solicita, seleccione *Sí* para aceptar los certificados de seguridad.


.Resultado
Tanto los sitios protegidos como los de recuperación aparecerán en el cuadro de diálogo objetos.
