---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Los back-ends de almacenamiento son los sistemas que los hosts ESXi utilizan para el almacenamiento de datos. 
---
= Añada un back-end de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Añadir un back-end de almacenamiento le permite incorporar un clúster de ONTAP.

*Acerca de esta tarea*

En caso de configuraciones de multi-tenancy en las que vCenter actúa como el inquilino con una SVM asociada, utilice ONTAP tools Manager para añadir el clúster. Asocie el back-end de almacenamiento con vCenter Server para asignarlo globalmente a la instancia integrada de vCenter Server. El inquilino de vCenter debe incorporar las máquinas virtuales de almacenamiento (SVM) que desee. Esto permite que un usuario de SVM aprovisione un almacén de datos vVols. Puede añadir almacenamiento en vCenter mediante la SVM.

Añada los back-ends de almacenamiento local con credenciales del clúster o de SVM mediante la interfaz de usuario de las herramientas de ONTAP. Estos back-ends de almacenamiento están limitados a una única instancia de vCenter. Cuando se usan las credenciales del clúster localmente, las SVM asociadas se asignan automáticamente a vCenter para gestionar vVols o VMFS. Para la gestión de VMFS, incluido el SRA, las herramientas de ONTAP admiten credenciales de SVM sin necesidad de un clúster global.

[role="tabbed-block"]
====
.Mediante el Administrador de herramientas de ONTAP
--

NOTE: En una configuración multi-tenant, puede añadir un clúster back-end de almacenamiento de forma global y SVM de forma local para usar las credenciales de usuario de SVM.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Añada el back-end de almacenamiento y proporcione la dirección IP del servidor o el FQDN, el nombre de usuario y los detalles de la contraseña.
+

NOTE: Se admiten los LIF de gestión de direcciones IPv4 y IPv6.



--
.Mediante la interfaz de usuario del cliente de vSphere
--

NOTE: Cuando se configura un back-end de almacenamiento a través de la interfaz de usuario del cliente de vSphere, es importante tener en cuenta que el almacén de datos vVols no admite la adición directa de un usuario de SVM.

. Inicie sesión en el cliente de vSphere.
. En la página de accesos directos, seleccione *Herramientas de NetApp ONTAP* en la sección de plugins.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Añada el back-end de almacenamiento y proporcione la dirección IP del servidor, el nombre de usuario, la contraseña y los detalles del puerto.
+

NOTE: Para añadir un usuario de SVM directamente, puede añadir credenciales basadas en clúster y LIF de gestión de direcciones IPv4 y IPv6, o bien proporcionar credenciales basadas en SVM con un LIF de gestión de SVM.



.¿Cuál es el siguiente?
La lista se actualizará y podrá ver el back-end de almacenamiento que acaba de añadir en la lista.

--
====