---
permalink: configure/configure-user-role-and-privileges.html 
sidebar: sidebar 
keywords: user roles 
summary: Es posible configurar nuevos roles de usuario para gestionar back-ends de almacenamiento mediante el archivo JSON proporcionado con las herramientas de ONTAP para VMware vSphere y ONTAP System Manager. 
---
= Configure los roles y privilegios de usuario de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible configurar nuevos roles y privilegios de usuario para gestionar back-ends de almacenamiento mediante el archivo JSON proporcionado con las herramientas de ONTAP para VMware vSphere y el administrador del sistema de ONTAP.

.Antes de empezar
* Debe haber descargado el archivo de privilegios de ONTAP desde las herramientas de ONTAP para VMware vSphere mediante _\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip_.
* Debería haber descargado el archivo ONTAP Privileges desde las herramientas de ONTAP utilizando `\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip`.
+

NOTE: Puede crear usuarios en el clúster o directamente en el nivel de las máquinas virtuales de almacenamiento (SVM). También puede crear usuarios sin utilizar el archivo user_roles.json y, si hace esto, debe tener un conjunto mínimo de privilegios en el nivel de SVM.

* Debe haber iniciado sesión con privilegios de administrador para el back-end de almacenamiento.


.Pasos
. Extraiga el archivo descargado _\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip_.
. Acceda a ONTAP System Manager mediante la dirección IP de gestión del clúster.
. Inicie sesión en el clúster con la Privileges de administrador. Para configurar un usuario, realice los siguientes pasos:
+
.. Para configurar el usuario de las herramientas ONTAP del clúster, seleccione el panel *Clúster* > *Configuración* > *Usuarios y roles*.
.. Para configurar el usuario de las herramientas ONTAP de SVM, seleccione el panel *SVM de almacenamiento* > *Configuración* > *Usuarios y roles*.
.. Seleccione *Agregar* en Usuarios.
.. En el cuadro de diálogo *Agregar usuario*, seleccione *Productos de virtualización*.
.. *Examinar* para seleccionar y cargar el archivo JSON de privilegios ONTAP.
+
El campo Producto se rellena automáticamente.

.. Seleccione la capacidad necesaria en el menú desplegable Capacidad del producto.
+
El campo *Rol* se rellena automáticamente según la capacidad del producto seleccionada.

.. Introduzca el nombre de usuario y la contraseña necesarios.
.. Seleccione la función Privileges (Detección, Crear almacenamiento, Modificar almacenamiento, Destruir almacenamiento, Función NAS/SAN) necesaria para el usuario y, a continuación, seleccione *Agregar*.




Se agregan el nuevo rol y usuario, y puede ver los privilegios detallados bajo el rol que ha configurado.



== Requisitos de asignación de agregados de SVM

Para usar credenciales de usuario de SVM para aprovisionar almacenes de datos, las herramientas de ONTAP internamente para VMware vSphere crean volúmenes en el agregado especificado en los almacenes de datos POSTERIORES a la API. ONTAP no permite la creación de volúmenes en agregados sin asignar en una SVM usando credenciales de usuario de SVM. Para resolver esto, debe asignar las SVM con los agregados usando la API de REST o la interfaz de línea de comandos de ONTAP como se describe aquí.

API DE REST:

[listing]
----
PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"aggregates":{"name":["aggr1","aggr2","aggr3"]}}'
----
CLI de ONTAP:

[listing]
----
sti115_vsim_ucs630f_aggr1 vserver show-aggregates                                        AvailableVserver        Aggregate      State         Size Type    SnapLock Type-------------- -------------- ------- ---------- ------- --------------svm_test       sti115_vsim_ucs630f_aggr1                               online     10.11GB vmdisk  non-snaplock
----


== Crear el usuario y el rol de ONTAP manualmente

Siga las instrucciones de esta sección para crear el usuario y los roles manualmente sin utilizar el archivo JSON.

. Acceda a ONTAP System Manager mediante la dirección IP de gestión del clúster.
. Inicie sesión en el clúster con la Privileges de administrador.
+
.. Para configurar las funciones de las herramientas ONTAP de clúster, seleccione el panel *Clúster* > *Configuración* > *Usuarios y roles*.
.. Para configurar las funciones de las herramientas ONTAP de SVM de clúster, seleccione el panel *Storage SVM* > *Settings* > *Users and Roles*


. Crear Roles:
+
.. Seleccione *Agregar* en la tabla *Roles*.
.. Introduzca los detalles de *nombre de rol* y *atributos de rol*.
+
Agregue la *REST API Path* y el acceso respectivo desde el menú desplegable.

.. Agregue todas las API necesarias y guarde los cambios.


. Crear usuarios:
+
.. Seleccione *Agregar* en la tabla *Usuarios*.
.. En el cuadro de diálogo *Agregar usuario*, seleccione *Administrador del sistema*.
.. Introduzca el *Nombre de usuario*.
.. Seleccione *Rol* de las opciones creadas en el paso *Crear Roles* anterior.
.. Introduzca las aplicaciones a las que desea acceder y el método de autenticación. ONTAPI y HTTP son las aplicaciones requeridas, y el tipo de autenticación es *Password*.
.. Establezca la *Contraseña para el usuario* y *Guardar* para el usuario.






=== Lista de privilegios mínimos necesarios para el usuario de cluster de ámbito global no administrativo

En esta sección se enumeran los privilegios mínimos necesarios para el usuario de cluster de ámbito global no administrador creado sin utilizar el archivo JSON de los usuarios. Si se agrega un clúster en el ámbito local, se recomienda utilizar el archivo JSON para crear los usuarios, ya que las herramientas de ONTAP para VMware vSphere requieren mucho más que solo los privilegios de lectura para aprovisionar en ONTAP.

Uso de las API:

|===


| API | Nivel de acceso | Se utiliza para 


| /api/clúster | Solo lectura | Detección de la configuración del clúster 


| /api/cluster/licencias/licencias | Solo lectura | Comprobación de licencia para licencias específicas de protocolo 


| /api/cluster/nodos | Solo lectura | Detección de tipo de plataforma 


| /api/seguridad/cuentas | Solo lectura | Detección de privilegios 


| /api/seguridad/roles | Solo lectura | Detección de privilegios 


| /api/almacenamiento/agregados | Solo lectura | Comprobación de espacio agregado durante el aprovisionamiento de almacenes de datos/volúmenes 


| /api/almacenamiento/clúster | Solo lectura | Para obtener el nivel del clúster Datos de espacio y eficiencia 


| /api/storage/disks | Solo lectura | Para obtener los discos asociados a un agregado 


| /api/almacenamiento/qos/políticas | Lectura/Crear/Modificar | QoS y gestión de políticas de máquinas virtuales 


| /api/svm/svm | Solo lectura | Para obtener la configuración de SVM en caso de que se añada el clúster de forma local. 


| /api/network/ip/interfaces | Solo lectura | Agregar entorno de administración de almacenamiento: Para identificar el alcance de la LIF de gestión es Cluster/SVM 
|===


=== Cree herramientas de ONTAP para usuario de ámbito de clúster basado en la API de VMware vSphere ONTAP


NOTE: Es necesario detectar, crear, modificar y destruir Privileges para realizar operaciones DE PARCHES y revertir automáticamente en caso de fallo en los almacenes de datos. La falta de todas estas Privileges juntas produce interrupciones en el flujo de trabajo y problemas de limpieza.

Crear herramientas de ONTAP para usuario basado en API de VMware vSphere ONTAP con detección, crear almacenamiento, modificar almacenamiento y destruir almacenamiento Privileges permite iniciar detecciones y gestionar flujos de trabajo de herramientas de ONTAP.

Para crear un usuario de ámbito de cluster con todas las Privileges mencionadas anteriormente, ejecute los siguientes comandos:

[listing]
----

security login rest-role create -role <role-name> -api /api/application/consistency-groups -access all

security login rest-role create -role <role-name> -api /api/private/cli/snapmirror -access all

security login rest-role create -role <role-name> -api /api/protocols/nfs/export-policies -access all

security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystem-maps -access all

security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystems -access all

security login rest-role create -role <role-name> -api /api/protocols/san/igroups -access all

security login rest-role create -role <role-name> -api /api/protocols/san/lun-maps -access all

security login rest-role create -role <role-name> -api /api/protocols/san/vvol-bindings -access all

security login rest-role create -role <role-name> -api /api/snapmirror/relationships -access all

security login rest-role create -role <role-name> -api /api/storage/volumes -access all

security login rest-role create -role <role-name> -api "/api/storage/volumes/*/snapshots" -access all

security login rest-role create -role <role-name> -api /api/storage/luns -access all

security login rest-role create -role <role-name> -api /api/storage/namespaces -access all

security login rest-role create -role <role-name> -api /api/storage/qos/policies -access all

security login rest-role create -role <role-name> -api /api/cluster/schedules -access read_create

security login rest-role create -role <role-name> -api /api/snapmirror/policies -access read_create

security login rest-role create -role <role-name> -api /api/storage/file/clone -access read_create

security login rest-role create -role <role-name> -api /api/storage/file/copy -access read_create

security login rest-role create -role <role-name> -api /api/support/ems/application-logs -access read_create

security login rest-role create -role <role-name> -api /api/protocols/nfs/services -access read_modify

security login rest-role create -role <role-name> -api /api/cluster -access readonly

security login rest-role create -role <role-name> -api /api/cluster/jobs -access readonly

security login rest-role create -role <role-name> -api /api/cluster/licensing/licenses -access readonly

security login rest-role create -role <role-name> -api /api/cluster/nodes -access readonly

security login rest-role create -role <role-name> -api /api/cluster/peers -access readonly

security login rest-role create -role <role-name> -api /api/name-services/name-mappings -access readonly

security login rest-role create -role <role-name> -api /api/network/ethernet/ports -access readonly

security login rest-role create -role <role-name> -api /api/network/fc/interfaces -access readonly

security login rest-role create -role <role-name> -api /api/network/fc/logins -access readonly

security login rest-role create -role <role-name> -api /api/network/fc/ports -access readonly

security login rest-role create -role <role-name> -api /api/network/ip/interfaces -access readonly

security login rest-role create -role <role-name> -api /api/protocols/nfs/kerberos/interfaces -access readonly

security login rest-role create -role <role-name> -api /api/protocols/nvme/interfaces -access readonly

security login rest-role create -role <role-name> -api /api/protocols/san/fcp/services -access readonly

security login rest-role create -role <role-name> -api /api/protocols/san/iscsi/services -access readonly

security login rest-role create -role <role-name> -api /api/security/accounts -access readonly

security login rest-role create -role <role-name> -api /api/security/roles -access readonly

security login rest-role create -role <role-name> -api /api/storage/aggregates -access readonly

security login rest-role create -role <role-name> -api /api/storage/cluster -access readonly

security login rest-role create -role <role-name> -api /api/storage/disks -access readonly

security login rest-role create -role <role-name> -api /api/storage/qtrees -access readonly

security login rest-role create -role <role-name> -api /api/storage/quota/reports -access readonly

security login rest-role create -role <role-name> -api /api/storage/snapshot-policies -access readonly

security login rest-role create -role <role-name> -api /api/svm/peers -access readonly

security login rest-role create -role <role-name> -api /api/svm/svms -access readonly

----
Además, para las versiones 9.16.0 y posteriores de ONTAP, ejecute el siguiente comando:

[listing]
----
security login rest-role create -role <role-name> -api /api/storage/storage-units -access all
----


=== Create ONTAP tools for VMware vSphere ONTAP API based SVM scoped user

Para crear un usuario de ámbito de SVM con toda la Privileges, ejecute los siguientes comandos:

[listing]
----
security login rest-role create -role <role-name> -api /api/application/consistency-groups -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/private/cli/snapmirror -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/nfs/export-policies -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystem-maps -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystems -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/san/igroups -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/san/lun-maps -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/san/vvol-bindings -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/snapmirror/relationships -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/volumes -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api "/api/storage/volumes/*/snapshots" -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/luns -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/namespaces -access all -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/cluster/schedules -access read_create -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/snapmirror/policies -access read_create -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/file/clone -access read_create -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/file/copy -access read_create -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/support/ems/application-logs -access read_create -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/nfs/services -access read_modify -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/cluster -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/cluster/jobs -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/cluster/peers -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/name-services/name-mappings -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/network/ethernet/ports -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/network/fc/interfaces -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/network/fc/logins -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/network/ip/interfaces -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/nfs/kerberos/interfaces -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/nvme/interfaces -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/san/fcp/services -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/protocols/san/iscsi/services -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/security/accounts -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/security/roles -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/qtrees -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/quota/reports -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/storage/snapshot-policies -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/svm/peers -access readonly -vserver <vserver-name>

security login rest-role create -role <role-name> -api /api/svm/svms -access readonly -vserver <vserver-name>
----
Además, para las versiones 9.16.0 y posteriores de ONTAP, ejecute el siguiente comando:

[listing]
----
security login rest-role create -role <role-name> -api /api/storage/storage-units -access all -vserver <vserver-name>
----
Para crear un nuevo usuario basado en API utilizando los roles basados en API creados anteriormente, ejecute el siguiente comando:

[listing]
----
security login create -user-or-group-name <user-name> -application http -authentication-method password -role <role-name> -vserver <cluster-or-vserver-name>
----
Ejemplo:

[listing]
----
security login create -user-or-group-name testvpsraall -application http -authentication-method password -role OTV_10_VP_SRA_Discovery_Create_Modify_Destroy -vserver C1_sti160-cluster_
----
Para desbloquear la cuenta, para habilitar el acceso a la interfaz de gestión, ejecute el siguiente comando:

[listing]
----
security login unlock -user <user-name> -vserver <cluster-or-vserver-name>
----
Ejemplo:

[listing]
----
security login unlock -username testvpsraall -vserver C1_sti160-cluster
----


== Actualice las herramientas de ONTAP para un usuario de VMware vSphere 10,1 a 10,3 usuario

Si el usuario de las herramientas de ONTAP para VMware vSphere 10,1 es un usuario de ámbito de clúster creado mediante el archivo json, ejecute los siguientes comandos en la interfaz de línea de comandos de ONTAP utilizando el usuario admin para actualizar a la versión 10,3.

Para las capacidades del producto:

* VSC
* VSC y proveedor VASA
* VSC y SRA
* VSC, proveedor VASA y SRA.


Privileges de clúster:

_security login role create -role <existing-role-name> -cmddirname «vserver nvme namespace show» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem show» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem host show» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem map show» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme show-interface» -access read_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem host add» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem map add» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme namespace delete» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem delete» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem host remove» -access all_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem map remove» -access all_

Si el usuario de las herramientas de ONTAP para VMware vSphere 10,1 es un usuario de ámbito SVM creado con el archivo json, ejecute los siguientes comandos en la interfaz de línea de comandos de ONTAP utilizando el usuario admin para actualizar a la versión 10,3.

Privileges de SVM:

_security login role create -role <existing-role-name> -cmddirname «vserver nvme namespace show» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem show» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem host show» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem map show» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme show-interface» -access read -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem host add» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem map add» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme namespace delete» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem delete» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem host remove» -access all -vserver <vserver-name>_

_security login role create -role <existing-role-name> -cmddirname «vserver nvme subsystem map remove» -access all -vserver <vserver-name>_

Al agregar el comando _vserver nvme namespace show_ y _vserver nvme subsystem show_ al rol existente, se agregan los siguientes comandos.

[listing]
----
vserver nvme namespace create

vserver nvme namespace modify

vserver nvme subsystem create

vserver nvme subsystem modify

----