---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: Si no se configuró el acceso a la red, de forma predeterminada todas las direcciones IP detectadas desde el host ESXi se añaden a la política de exportación. 
---
= Configure el acceso a la red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no se configuró el acceso a la red, de forma predeterminada todas las direcciones IP detectadas del host ESXi se añadirán a la política de exportación. Puede configurarlo para agregar algunas direcciones IP específicas a la política de exportación y excluir el resto. Sin embargo, cuando se realiza una operación de montaje en los hosts ESXi excluidos, la operación genera un error.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Seleccione *Herramientas de NetApp ONTAP* en la página de accesos directos en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP, navegue hasta *Ajustes* > *Administrar acceso a la red* > *Editar*.
+
Para agregar varias direcciones IP, separe la lista con comas, rango, enrutamiento entre dominios sin clases (CIDR) o una combinación de los tres.

. Seleccione *Guardar*.

