---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: Cuando se ejecutan por primera vez herramientas de ONTAP para VMware vSphere en un cliente vSphere, las herramientas de ONTAP para VMware vSphere detectan los hosts ESXi, sus LUN y exportaciones de NFS, así como los sistemas de almacenamiento NetApp propietarios de esos LUN y exportaciones. 
---
= Detectar sistemas de almacenamiento y hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se ejecutan por primera vez herramientas de ONTAP para VMware vSphere en un cliente vSphere, las herramientas de ONTAP detectan los hosts ESXi, sus LUN y exportaciones NFS, y los sistemas de almacenamiento de NetApp propietarios de esos LUN y exportaciones.

.Antes de empezar
* Todos los hosts ESXi deben estar encendidos y conectados.
* Debe estar en ejecución todas las máquinas virtuales de almacenamiento que se vayan a detectar y cada nodo del clúster debe tener al menos una LIF de datos configurada para el protocolo de almacenamiento en uso (NFS o iSCSI).


*Acerca de esta tarea*

Puede detectar nuevos sistemas de almacenamiento o actualizar información sobre los sistemas de almacenamiento existentes para obtener la información más reciente sobre la configuración y la capacidad en cualquier momento. También puede modificar las credenciales que usan las herramientas de ONTAP para VMware vSphere para iniciar sesión en los sistemas de almacenamiento.

Al detectar los sistemas de almacenamiento, las herramientas de ONTAP para VMware vSphere recopilan información de los hosts ESXi que gestiona la instancia de vCenter Server.

.Pasos
. En la página inicial de vSphere Client, seleccione *Hosts and Clusters*.
. Haga clic con el botón derecho del ratón en el centro de datos requerido y seleccione *Herramientas de NetApp ONTAP* > *Actualizar datos de host* .
+
En el cuadro de diálogo *Confirmar*, confirme su elección.

. Seleccione los controladores de almacenamiento detectados que tengan el estado `Authentication Failure` y seleccione *Acciones* > *Modificar*.
. Rellene la información necesaria en el cuadro de diálogo *Modificar sistema de almacenamiento*.
. Repita los pasos 4 y 5 para todas las controladoras de almacenamiento con `Authentication Failure` estado.


Una vez completado el proceso de detección, realice las siguientes acciones:

* Utilice las herramientas de ONTAP para VMware vSphere para configurar las opciones del host ESXi para los hosts que muestran el icono de alerta en la columna de configuración del adaptador, la columna MPIO settings o la columna NFS settings.
* Proporcione las credenciales del sistema de almacenamiento.

