---
permalink: manage/change-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Puede cambiar la contraseña del administrador mediante el Administrador de herramientas de ONTAP. 
---
= Cambiar la contraseña del Administrador de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la contraseña del administrador mediante el Administrador de herramientas de ONTAP.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione el icono *administrator* en la esquina superior derecha de la pantalla y seleccione *Change password*.
. En la ventana emergente de cambio de contraseña, introduzca la contraseña antigua y los detalles de la nueva contraseña. La restricción para cambiar la contraseña se muestra en la pantalla de la interfaz de usuario.
. Selecciona *Cambiar* para implementar los cambios.

