---
permalink: manage/configure-remote-diagnostic-access.html 
sidebar: sidebar 
keywords:  
summary: Puede configurar herramientas de ONTAP para VMware vSphere a fin de habilitar el acceso SSH para el usuario diag. 
---
= Configurar el acceso de diagnóstico remoto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar herramientas de ONTAP para VMware vSphere a fin de habilitar el acceso SSH para el usuario diag.

.Antes de empezar
La extensión VASA Provider debe habilitarse para la instancia de vCenter Server.

*Acerca de esta tarea*

El uso de SSH para acceder a la cuenta de usuario diag tiene las siguientes limitaciones:

* Solo se le permite una cuenta de inicio de sesión por cada activación de SSH.
* El acceso SSH a la cuenta de usuario de diagnóstico se deshabilita cuando se produce alguna de las siguientes situaciones:
+
** La hora caduca.
+
La sesión de inicio de sesión solo será válida hasta la medianoche del día siguiente.

** Inicie sesión como usuario diag de nuevo con SSH.




.Pasos
. Desde vCenter Server, abra una consola al proveedor VASA.
. Inicie sesión como el usuario de mantenimiento.
. Introduzca `4` para seleccionar Soporte y diagnóstico.
. Introduzca `2` para seleccionar Habilitar acceso a diagnóstico remoto.
. Introduzca `y` en el cuadro de diálogo Confirmación para habilitar el acceso de diagnóstico remoto.
. Introduzca una contraseña para el acceso de diagnóstico remoto.

