---
permalink: manage/migrate-standard-virtual-machines-to-vvols-datastores.html 
sidebar: sidebar 
keywords: Migrate NFS and VMFS virtual machines 
summary: 'Puede migrar máquinas virtuales de almacenes de datos NFS y VMFS a almacenes de datos Virtual Volumes \(vVols\) para aprovechar la gestión de máquinas virtuales basada en políticas y otras funcionalidades de vVols. Los almacenes de datos de vVols le permiten satisfacer requisitos cada vez mayores de las cargas de trabajo.' 
---
= Migre máquinas virtuales con almacenes de datos NFS y VMFS a almacenes de datos vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede migrar máquinas virtuales de almacenes de datos NFS y VMFS a almacenes de datos Virtual Volumes (vVols) para aprovechar la gestión de máquinas virtuales basada en políticas y otras capacidades de vVols. Los almacenes de datos de vVols permiten satisfacer requisitos cada vez mayores de las cargas de trabajo.

.Antes de empezar
Compruebe que el proveedor VASA no esté en ejecución en ninguna de las máquinas virtuales que planifique migrar. Si migra una máquina virtual que ejecuta VASA Provider a un almacén de datos vVols, no podrá realizar ninguna operación de gestión, incluida la activación de las máquinas virtuales que se encuentran en almacenes de datos vVols.

*Acerca de esta tarea*

Cuando se migra de un almacén de datos NFS y VMFS a un almacén de datos vVols, la instancia de vCenter Server utiliza las API de vStorage para la integración de cabinas (VAAI) descarga las cargas al mover datos de almacenes de datos VMFS, pero no de un archivo VMDK NFS. Las descargas de VAAI suelen reducir la carga en el host.

.Pasos
. Haga clic con el botón derecho en la máquina virtual que desea migrar y seleccione *Migrate*.
. Seleccione *Cambiar solo almacenamiento* y luego seleccione *Siguiente*.
. Seleccione un formato de disco virtual, una política de almacenamiento de máquina virtual y un almacén de datos de VVol que coincida con las funciones del almacén de datos que desea migrar.
. Revise los ajustes y seleccione *Finalizar*.

