---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: El montaje de un almacén de datos permite acceder al almacenamiento a hosts adicionales. El almacén de datos se puede montar en los hosts adicionales después de añadir los hosts al entorno de VMware. 
---
= Montar almacenes de datos de NFS y VMFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El montaje de un almacén de datos permite acceder al almacenamiento a hosts adicionales. El almacén de datos se puede montar en los hosts adicionales después de añadir los hosts al entorno de VMware.

.Acerca de esta tarea
* Algunas acciones de clic con el botón derecho quedan deshabilitadas o no disponibles según la versión del cliente de vSphere y el tipo de almacén de datos seleccionado.
+
** Si utiliza vSphere Client 8,0 o versiones posteriores, algunas de las opciones del botón derecho están ocultas.
** Desde las versiones de vSphere 7.0U3 a vSphere 8,0, aunque aparezcan las opciones, la acción se desactivará.


* La opción mount datastore está deshabilitada cuando el clúster de hosts está protegido con configuraciones uniformes.


.Pasos
. En la página inicial de vSphere Client, seleccione *Hosts and Clusters*.
. En el panel de navegación de la izquierda, seleccione los centros de datos que contienen los hosts.
. Para montar almacenes de datos NFS/VMFS en host o clúster de hosts, haga clic con el botón derecho y seleccione *NetApp ONTAP tools* > *Mount datastores*.
. Seleccione los almacenes de datos que desea montar y seleccione *Mount*.


.El futuro
Puede realizar un seguimiento del progreso en el panel de tareas recientes.
