---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Si ha olvidado la contraseña del administrador de herramientas de ONTAP, puede restablecer las credenciales de administrador con el token generado por las herramientas de ONTAP para la consola de mantenimiento de VMware vSphere. 
---
= Restablezca la contraseña del administrador de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha olvidado la contraseña del administrador de herramientas de ONTAP, puede restablecer las credenciales de administrador con el token que generan las herramientas de ONTAP para la consola de mantenimiento de VMware vSphere.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. En la pantalla de inicio de sesión, seleccione la opción *Restablecer contraseña*.
+
Para restablecer la contraseña de administrador, tiene que generar el token de restablecimiento mediante las herramientas de ONTAP para la consola de mantenimiento de VMware vSphere.

+
.. Desde vCenter Server, abra la consola de mantenimiento
.. Introduzca '2' para seleccionar la opción de configuración del sistema
.. Introduzca '3' para cambiar la contraseña de usuario 'antigua'.


. En la ventana emergente de cambio de contraseña, introduzca el token de restablecimiento de contraseña, el nombre de usuario y los detalles de la nueva contraseña.
. Seleccione *Restablecer* para implementar los cambios. Cuando se restablezca correctamente la contraseña, puede usar la nueva contraseña para iniciar sesión.

